const BAD_REQUEST_STATUS_CODE = 400;
const NOT_FOUND_STATUS_CODE = 404;
const CONNFLICT_STATUS_CODE = 409;
const INTERNAL_SERVER_ERROR_STATUS_CODE = 500;
const FORBIDDEN_STATUS_CODE = 403;
const UNAUTHORIZED_STATUS_CODE = 401;
const USER_NOT_FOUND = "User not found";
const INVALID_USER_ID_FORMAT = "Invalid user ID format";
const INVALID_URL = "You must enter a valid URL";

module.exports = {
  BAD_REQUEST_STATUS_CODE,
  NOT_FOUND_STATUS_CODE,
  CONNFLICT_STATUS_CODE,
  UNAUTHORIZED_STATUS_CODE,
  INTERNAL_SERVER_ERROR_STATUS_CODE,
  FORBIDDEN_STATUS_CODE,
  USER_NOT_FOUND,
  INVALID_USER_ID_FORMAT,
  INVALID_URL,
};
