const BAD_REQUEST_STATUS_CODE = 400;
const NOT_FOUND_STATUS_CODE = 404;
const INTERNAL_SERVER_ERROR_STATUS_CODE = 500;

const USER_NOT_FOUND = "User not found";
const INVALID_USER_ID_FORMAT = "Invalid user ID format";
const INVALID_URL = "You must enter a valid URL";

module.exports = {
  BAD_REQUEST_STATUS_CODE,
  NOT_FOUND_STATUS_CODE,
  INTERNAL_SERVER_ERROR_STATUS_CODE,
  USER_NOT_FOUND,
  INVALID_USER_ID_FORMAT,
  INVALID_URL,
};
